# vim:ft=ansible:
---
- hosts: docker-hosts
  sudo: yes
  vars:
    app_name: "ecarmi.org_nanoc"
    build_dir: /var/apps
    app_repo: "{{ build_dir }}/{{ app_name }}"
    image_tag: latest
    image_name: "ecarmi_org_nginx"
  tasks:
    - name: install apt packages
      apt: "name='{{ item }}' state=present"
      with_items:
        - git
        - python-pip
      tags:
        - server_setup

    - name: install docker-py
      pip: name=docker-py version=0.7.1
      tags:
        - server_setup

    - name: create build directory
      file: >
        dest="{{ build_dir }}"
        state=directory
    - name: clone git repo into build directory
      git: >
        repo="https://github.com/carmi/ecarmi.org-nanoc.git"
        dest="{{ app_repo }}"
        accept_hostkey=True
        version="HEAD"
      register: git_clone_result

    - name: build new docker image
      docker_image: >
        name="{{ image_name }}"
        tag="{{ image_tag }}"
        path="{{ app_repo }}"
        state=build
      when: git_clone_result|changed

    - name: Stop old image
      shell: "docker stop {{ image_name }}"
      ignore_errors: yes

    - name: Remove old image
      shell: "docker rm {{ image_name }}"
      ignore_errors: yes

    - name: Run new image
      shell: >
               . /root/.bashrc &&
               docker run -d
               --restart=on-failure:5
               -p $ECARMI_ORG_1_PORT:80
               -v /srv/ecarmi_org/output:/srv/www/ecarmi.org/prd
               --name {{ image_name }}
               {{ image_name }}:latest
